name: 'Install Rust toolchain'
description: 'Install a rust toolchain'

inputs:
  toolchain:
    description: 'Default toolchain to install'
    required: false
    default: 'stable'

runs:
  using: composite
  steps:
    - name: Install Rust
      shell: bash
      id: select
      run: echo "version=${{ inputs.toolchain }}" >> "$GITHUB_OUTPUT"

    - name: Install Rust
      shell: bash
      run: |
        rustup set profile minimal
        rustup update "${{ steps.select.outputs.version }}" --no-self-update
        rustup default "${{ steps.select.outputs.version }}"
        echo RUSTFLAGS="-D warnings" >> "$GITHUB_ENV"
